"""connect tables has_many to has_many

Revision ID: f0ede71968ab
Revises: a6406e795d69
Create Date: 2023-06-11 18:57:46.065689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ede71968ab'
down_revision = 'a6406e795d69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
